######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 13:36:12 2018
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
QT += widgets
