######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 14:57:41 2018
######################################################################

TEMPLATE = app
TARGET = layout
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
QT += widgets
