######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 14:11:10 2018
######################################################################

TEMPLATE = app
TARGET = quit
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
QT += widgets
