######################################################################
# Automatically generated by qmake (3.0) Sat Oct 13 23:33:55 2018
######################################################################

TEMPLATE = app
TARGET = find
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
QT += widgets
