######################################################################
# Automatically generated by qmake (3.0) Sun Oct 14 11:28:46 2018
######################################################################

TEMPLATE = app
TARGET = find
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp

QT += widgets